name: dart_cli_chatai
description: A CLI application Chat AI
version: 1.0.0

executables:
  main: bin/dart_cli_chatai.dart

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.18.1
  http: ^1.4.0
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0